
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de Bord',
    'nav.playerAnalysis': 'Analyse des Joueurs',
    'nav.teamPerformance': 'Performance de l\'Équipe',
    'nav.reports': 'Rapports',
    'nav.settings': 'Paramètres',
    'nav.individualStats': 'Analyses Individuelles',
    'nav.playerComparison': 'Comparaison des Joueurs',
    'nav.playerDevelopment': 'Développement des Joueurs',
    'nav.shotMap': 'Carte des Tirs',
    'nav.teamOverview': 'Aperçu de l\'Équipe',
    'nav.tacticalAnalysis': 'Analyse Tactique',
    'nav.pointsDeductions': 'Pénalités de Points',
    'nav.matchDataImport': 'Import Données Match',
    'nav.aiAnalytics': 'Analyses IA',
    'nav.goalsAssists': 'Buts et Passes Décisives',
    'header.title': 'Striker Insights Arena',
    'header.dashboard': 'Tableau de Bord',

    // Common Actions & UI
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.refresh': 'Actualiser',
    'common.export': 'Exporter',
    'common.save': 'Sauvegarder',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.select': 'Sélectionner',
    'common.selectPlayer': 'Sélectionner un joueur',
    'common.noData': 'Aucune donnée disponible',
    'common.toggleSidebar': 'Basculer la barre latérale',
    'common.refreshData': 'Actualiser les données',
    'common.selected': 'sélectionnés',

    // Player-specific terms
    'player.position': 'Position',
    'player.age': 'Âge',
    'player.height': 'Taille',
    'player.weight': 'Poids',
    'player.nationality': 'Nationalité',
    'player.goals': 'Buts',
    'player.assists': 'Passes décisives',
    'player.matches': 'Matchs',
    'player.matchesPlayed': 'Matchs joués',
    'player.goalsScored': 'Buts marqués',
    'player.matchRating': 'Note du match',
    'player.passAccuracy': 'Précision des passes',
    'player.shotsOnTarget': 'Tirs cadrés',
    'player.distanceCovered': 'Distance parcourue',
    'player.tackles': 'Tacles',
    'player.interceptions': 'Interceptions',
    'player.fouls': 'Fautes',
    'player.yellowCards': 'Cartons jaunes',
    'player.redCards': 'Cartons rouges',
    'player.manOfMatch': 'Homme du match',
    'player.conversionRate': 'Taux de conversion',
    'player.aerialDuels': 'Duels aériens',
    'player.keyPasses': 'Passes clés',
    'player.saves': 'Arrêts',
    'player.cleanSheets': 'Cages inviolées',
    'player.distribution': 'Distribution',

    // Dashboard sections
    'dashboard.teamMetrics': 'Métriques Équipe',
    'dashboard.playerPerformance': 'Performance Joueur',
    'dashboard.recentMatches': 'Matchs Récents',
    'dashboard.upcomingFixtures': 'Prochains Matchs',
    'dashboard.squadOverview': 'Aperçu Effectif',
    'dashboard.injuryList': 'Liste Blessures',
    'dashboard.trainingSchedule': 'Programme Entraînement',
    'dashboard.complianceAlerts': 'Alertes Conformité',
    'dashboard.systemStatus': 'État Système',
    'dashboard.analyticsOverview': 'Aperçu Analytique',
    'dashboard.executiveSummary': 'Résumé Exécutif',
    'dashboard.strategicOverview': 'Vue Stratégique',

    // Match contexts
    'match.home': 'Domicile',
    'match.away': 'Extérieur',
    'match.neutral': 'Terrain neutre',
    'match.win': 'Victoire',
    'match.loss': 'Défaite',
    'match.draw': 'Match nul',
    'match.upcoming': 'À venir',
    'match.completed': 'Terminé',
    'match.cancelled': 'Annulé',
    'match.postponed': 'Reporté',

    // Formations & Tactics
    'formation.442': '4-4-2',
    'formation.433': '4-3-3',
    'formation.352': '3-5-2',
    'formation.451': '4-5-1',
    'formation.343': '3-4-3',
    'formation.532': '5-3-2',
    'tactics.formation': 'Formation tactique',
    'tactics.passingNetwork': 'Réseau de passes',
    'tactics.heatmap': 'Carte de chaleur',
    'tactics.analysis': 'Analyse tactique',

    // Positions
    'position.goalkeeper': 'Gardien',
    'position.defender': 'Défenseur',
    'position.midfielder': 'Milieu de terrain',
    'position.forward': 'Attaquant',
    'position.striker': 'Buteur',
    'position.winger': 'Ailier',
    'position.fullback': 'Arrière latéral',
    'position.centerback': 'Défenseur central',
    'position.defensiveMidfielder': 'Milieu défensif',
    'position.attackingMidfielder': 'Milieu offensif',

    // Time periods
    'time.season': 'Saison',
    'time.month': 'Mois',
    'time.week': 'Semaine',
    'time.last30days': '30 derniers jours',
    'time.last7days': '7 derniers jours',
    'time.thisMonth': 'Ce mois',
    'time.lastMonth': 'Mois dernier',
    'time.thisSeason': 'Cette saison',
    'time.lastSeason': 'Saison dernière',

    // Reports & Analytics
    'reports.generate': 'Générer rapport',
    'reports.export': 'Exporter rapport',
    'reports.performance': 'Rapport performance',
    'reports.tactical': 'Rapport tactique',
    'reports.individual': 'Rapport individuel',
    'reports.team': 'Rapport équipe',
    'reports.development': 'Rapport développement',
    'reports.injury': 'Rapport blessures',
    'analytics.advanced': 'Analyses avancées',
    'analytics.predictive': 'Analyses prédictives',
    'analytics.benchmark': 'Analyse comparative',
    'analytics.trends': 'Tendances',

    // User roles & permissions
    'role.player': 'Joueur',
    'role.coach': 'Entraîneur',
    'role.analyst': 'Analyste',
    'role.performanceDirector': 'Directeur Performance',
    'role.management': 'Direction',
    'role.admin': 'Administrateur',
    'role.unassigned': 'Non assigné',

    // Unassigned Role Dashboard
    'unassigned.welcome': 'Bienvenue sur Striker Insights Arena',
    'unassigned.accountCreated': 'Votre compte a été créé avec succès',
    'unassigned.roleAssignmentPending': 'Attribution de Rôle en Attente',
    'unassigned.accessLimited': 'Votre compte a été créé, mais aucun rôle ne vous a encore été attribué. Votre accès aux fonctionnalités sera limité jusqu\'à ce qu\'un administrateur vous attribue le rôle approprié.',
    'unassigned.nextStepsTitle': 'Que se passe-t-il ensuite ?',
    'unassigned.step1': 'Un administrateur examinera votre compte et vous attribuera le rôle approprié en fonction de votre position au sein de l\'organisation.',
    'unassigned.step2': 'Une fois votre rôle attribué, vous aurez accès aux fonctionnalités et aux données pertinentes pour votre position.',
    'unassigned.step3': 'Vous recevrez une notification par email lorsque votre compte sera entièrement configuré.',
    'unassigned.contactAdmin': 'Contacter l\'Administrateur',
    'unassigned.viewDocs': 'Consulter la Documentation',
    'unassigned.needHelp': 'Si vous pensez qu\'il s\'agit d\'une erreur ou si vous avez des questions, veuillez contacter l\'administrateur système à',
    'unassigned.statusPending': 'Statut : En attente d\'attribution de rôle',
    'unassigned.estimatedTime': 'Temps d\'attribution estimé : 24-48 heures',
    'unassigned.roleTypes': 'Types de rôles disponibles',
    'unassigned.playerRole': 'Joueur - Accès aux statistiques personnelles et au développement',
    'unassigned.coachRole': 'Entraîneur - Gestion d\'équipe et analyse tactique',
    'unassigned.analystRole': 'Analyste - Outils d\'analyse avancés et rapports',
    'unassigned.directorRole': 'Directeur - Vue d\'ensemble stratégique et benchmarks',
    'unassigned.managementRole': 'Direction - Métriques exécutives et gouvernance',
    'unassigned.adminRole': 'Administrateur - Configuration système et gestion utilisateurs',

    // Coach Dashboard
    'coach.welcomeBack': 'Bon retour',
    'coach.manageTeam': 'Gérez les performances de votre équipe et suivez le développement des joueurs',
    'coach.squadSize': 'Effectif',
    'coach.activePlayers': 'Joueurs Actifs',
    'coach.playersAvailable': 'Joueurs Disponibles',
    'coach.readyForSelection': 'Prêts pour Sélection',
    'coach.injuries': 'Blessures',
    'coach.playersInjured': 'Joueurs Blessés',
    'coach.trainingAttendance': 'Présence Entraînement',
    'coach.thisWeek': 'Cette Semaine',
    'coach.teamGoals': 'Buts Équipe',
    'coach.thisSeason': 'Cette Saison',
    'coach.upcomingSuspensions': 'Suspensions à Venir',
    'coach.next3Matches': '3 Prochains Matchs',
    'coach.winRate': 'Taux de Victoire',
    'coach.form': 'Forme',
    'coach.last3Games': '3 Derniers Matchs',
    'coach.quickActions': 'Actions Rapides',
    'coach.teamSelection': 'Sélection Équipe',
    'coach.trainingPlan': 'Plan Entraînement',
    'coach.scheduleMatch': 'Programmer Match',
    'coach.setGoals': 'Définir Objectifs',
    'coach.playerFeedback': 'Retours Joueurs',
    'coach.matchReport': 'Rapport Match',
    'coach.upcomingSchedule': 'Prochains Événements',
    'coach.teamComplianceAlerts': 'Alertes Conformité Équipe',
    'coach.importantNotices': 'Avis importants pour votre équipe',
    'coach.playerInjuriesAlert': 'Blessures Joueurs',
    'coach.lowTrainingAttendance': 'Faible Présence Entraînement',
    'coach.allSystemsGreen': 'Tout est OK',
    'coach.noCriticalIssues': 'Aucun problème critique détecté avec votre effectif',

    // Login & Authentication
    'auth.welcomeBack': 'Bon retour',
    'auth.login': 'Connexion',
    'auth.register': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.showPassword': 'Afficher le mot de passe',
    'auth.hidePassword': 'Masquer le mot de passe',
    'auth.signInWithGoogle': 'Se connecter avec Google',
    'auth.loggingIn': 'Connexion...',
    'auth.registering': 'Inscription...',

    // Errors & Messages
    'error.failedToLoad': 'Échec du chargement',
    'error.failedToLoadPlayerData': 'Échec du chargement des données joueur',
    'error.noPlayerSelected': 'Aucun joueur sélectionné',
    'error.noDataAvailable': 'Aucune donnée disponible',
    'message.selectPlayerToView': 'Sélectionnez un joueur pour voir ses statistiques',
    'message.loadingPlayerProfile': 'Chargement du profil joueur...',
    'message.dataRefreshed': 'Données actualisées avec succès',
    'message.exportSuccess': 'Export réussi',
    'message.savingData': 'Sauvegarde des données...',

    // Performance metrics
    'metrics.goals': 'Buts',
    'metrics.assists': 'Passes décisives',
    'metrics.shots': 'Tirs',
    'metrics.shotsOnTarget': 'Tirs cadrés',
    'metrics.passes': 'Passes',
    'metrics.passAccuracy': 'Précision passes',
    'metrics.tackles': 'Tacles',
    'metrics.interceptions': 'Interceptions',
    'metrics.clearances': 'Dégagements',
    'metrics.blocks': 'Blocages',
    'metrics.fouls': 'Fautes',
    'metrics.offsides': 'Hors-jeu',
    'metrics.corners': 'Corners',
    'metrics.freeKicks': 'Coups francs',
    'metrics.penalties': 'Penalties',
    'metrics.crossAccuracy': 'Précision centres',
    'metrics.dribblesCompleted': 'Dribbles réussis',
    'metrics.aerialWins': 'Duels aériens gagnés',
    'metrics.recoveries': 'Récupérations',
    'metrics.possessionWon': 'Possession gagnée',
    'metrics.possessionLost': 'Possession perdue',

    // Squad management
    'squad.size': 'Taille effectif',
    'squad.available': 'Joueurs disponibles',
    'squad.injured': 'Blessés',
    'squad.suspended': 'Suspendus',
    'squad.training': 'Entraînement',
    'squad.attendance': 'Présence',
    'squad.fitness': 'Condition physique',
    'squad.development': 'Développement',
    'squad.planning': 'Planification effectif',
    'squad.value': 'Valeur effectif',

    // Management & Strategic
    'management.dashboard': 'Tableau de Bord Direction',
    'management.strategic': 'Vue Stratégique',
    'management.oversight': 'Supervision stratégique et gestion d\'équipe',
    'management.performance': 'Performance équipe',
    'management.standings': 'Classement actuel',
    'management.squadValue': 'Valeur effectif',
    'management.totalInvestment': 'Investissement total',
    'management.riskOverview': 'Vue risques',
    'management.adminStatus': 'Statut administratif',
    'management.seasonObjectives': 'Objectifs saison',
    'management.actions': 'Actions direction',
    'management.financialReport': 'Rapport financier',
    'management.contractManagement': 'Gestion contrats',
    'management.adminDashboard': 'Tableau de bord admin',
    'management.leaguePosition': 'Position championnat',
    'management.points': 'Points',
    'management.goalDiff': 'Diff buts',
    'management.yoyGrowth': 'Croissance annuelle',
    'management.expiring': 'Expirant',
    'management.activeRisks': 'Risques actifs',
    'management.highRisk': 'Risque élevé',
    'management.mediumRisk': 'Risque moyen',
    'management.onTrack': 'Sur la bonne voie',

    // Admin & System Administration
    'admin.dashboard': 'Tableau de Bord Admin',
    'admin.welcome': 'Bon retour, Administrateur',
    'admin.systemManagement': 'Gérer l\'administration système, la conformité et les contrôles d\'accès utilisateur',
    'admin.userManagement': 'Gestion Utilisateurs',
    'admin.userManagementDesc': 'Aperçu des comptes et statistiques',
    'admin.systemAdmin': 'Administration Système',
    'admin.systemAdminDesc': 'Configuration et piste d\'audit',
    'admin.dataPipeline': 'État Pipeline Données',
    'admin.dataPipelineDesc': 'Opérations import/export et santé système',
    'admin.compliance': 'Aperçu Conformité',
    'admin.complianceDesc': 'Statut de conformité et métriques',
    'admin.playersAtRisk': 'Joueurs à Risque',
    'admin.playersAtRiskDesc': 'Joueurs nécessitant une attention immédiate pour la conformité disciplinaire',
    'admin.systemStatus': 'État Système',
    'admin.playerAnalytics': 'Analytics Joueurs',
    'admin.coreFeatures': 'Fonctionnalités Principales',
    'admin.totalUsers': 'Total Utilisateurs',
    'admin.activeUsers': 'Actifs',
    'admin.pendingUsers': 'En attente',
    'admin.userRoles': 'Rôles Utilisateurs',
    'admin.addUser': 'Ajouter Utilisateur',
    'admin.manageRoles': 'Gérer Rôles',
    'admin.quickSettings': 'Paramètres Rapides',
    'admin.systemConfig': 'Config Système',
    'admin.permissions': 'Permissions',
    'admin.notifications': 'Notifications',
    'admin.apiAccess': 'Accès API',
    'admin.recentActivities': 'Activités Récentes',
    'admin.viewAuditLog': 'Voir Journal Audit',
    'admin.dataServices': 'Services Données',
    'admin.scheduleImport': 'Programmer Import',
    'admin.exportData': 'Exporter Données',
    'admin.systemDiagnostics': 'Diagnostics Système',
    'admin.databaseStatus': 'État Base de Données',
    'admin.apiServices': 'Services API',
    'admin.storage': 'Stockage',
    'admin.lastBackup': 'Dernière Sauvegarde',
    'admin.online': 'En ligne',
    'admin.operational': 'Opérationnel',
    'admin.used': 'Utilisé',
    'admin.today': 'Aujourd\'hui',
    'admin.userAdded': 'Utilisateur Ajouté',
    'admin.roleChanged': 'Rôle Modifié',
    'admin.dataImport': 'Import Données',
    'admin.systemUpdate': 'Mise à Jour Système',
    'admin.newAnalystAccount': 'Nouveau compte analyste créé',
    'admin.promotedToCoach': 'T. Williams promu Entraîneur',
    'admin.matchDataImported': 'Données match importées avec succès',
    'admin.dashboardDeployed': 'Tableau de bord v2.1 déployé',
    'admin.hoursAgo': 'heures',
    'admin.dayAgo': 'jour',
    'admin.daysAgo': 'jours',
    'admin.excellent': 'Conformité Excellente',
    'admin.attentionNeeded': 'Attention Nécessaire',
    'admin.urgentAction': 'Action Urgente Requise',
    'admin.complianceScore': 'Score Conformité',
    'admin.pointsDeducted': 'Points Déduits',
    'admin.activeViolations': 'Violations Actives',
    'admin.allSystems': 'Tous systèmes opérationnels',
    'admin.dataProcessing': 'Traitement données en direct',
    'admin.allFeatures': 'Toutes fonctionnalités activées',
    'management.achieved': 'Atteint',
    'management.midTable': 'Milieu de tableau',
    'management.cupQuarter': 'Quart finale coupe régionale',
    'management.youthProgram': 'Programme formation jeunes',

    // Development & Training
    'development.goals': 'Objectifs développement',
    'development.progress': 'Progrès',
    'development.milestones': 'Étapes importantes',
    'development.pathways': 'Parcours développement',
    'development.assessment': 'Évaluation',
    'development.feedback': 'Retours',
    'development.plan': 'Plan développement',
    'training.schedule': 'Programme entraînement',
    'training.intensity': 'Intensité',
    'training.load': 'Charge entraînement',
    'training.recovery': 'Récupération',

    // Injuries & Medical
    'injury.type': 'Type blessure',
    'injury.severity': 'Gravité',
    'injury.expectedReturn': 'Retour prévu',
    'injury.treatment': 'Traitement',
    'injury.status': 'Statut',
    'injury.active': 'Active',
    'injury.recovering': 'En récupération',
    'injury.minor': 'Mineure',
    'injury.moderate': 'Modérée',

    // Player Comparison Page
    'comparison.title': 'Comparaison des Joueurs',
    'comparison.subtitle': 'Comparez jusqu\'à 4 joueurs selon diverses métriques de performance',
    'comparison.playerSelection': 'Sélection des Joueurs',
    'comparison.selectedPlayers': 'Joueurs Sélectionnés',
    'comparison.availablePlayers': 'Joueurs Disponibles',
    'comparison.maxSelected': 'Joueurs maximum sélectionnés',
    'comparison.noAvailable': 'Aucun joueur disponible',
    'comparison.showMore': 'Afficher %d Joueurs Supplémentaires',
    'comparison.showLess': 'Afficher Moins',
    'comparison.matches': 'matchs',
    'comparison.selectAtLeastTwo': 'Sélectionnez au moins un autre joueur pour commencer la comparaison',
    'comparison.selectPlayersToStart': 'Sélectionnez des joueurs pour commencer à comparer leurs performances',
    'comparison.performanceAnalysis': 'Analyse Professionnelle de Performance',
    'comparison.comprehensiveMetrics': 'Métriques de performance complètes et analyse statistique',
    'comparison.categories': 'Catégories',
    'comparison.players': 'Joueurs',
    'comparison.bestAvg': 'Meilleur Moy',
    'comparison.range': 'Plage',
    'comparison.player': 'Joueur',
    'comparison.radarChart': 'Graphique Radar de Performance',
    'comparison.comprehensiveComparison': 'Comparaison de performance complète sur les métriques clés',
    'comparison.export': 'Exporter',
    'comparison.selectTwoOrMore': 'Sélectionnez 2 joueurs ou plus pour afficher le graphique radar',
    'comparison.playersComparison': 'Comparaison des Joueurs',
    'comparison.best': 'Meilleur',
    'comparison.excellent': 'Excellent',
    'comparison.good': 'Bon',
    'comparison.average': 'Moyen',
    'comparison.poor': 'Faible',
    'comparison.distance': 'Distance Totale',
    'comparison.distanceShort': 'Distance',
    'comparison.distanceMobile': 'Dist',
    'comparison.passCompletion': 'Précision des Passes',
    'comparison.passCompletionShort': 'Passes %',
    'comparison.passCompletionMobile': 'Passes',
    'comparison.shotsOnTarget': 'Tirs Cadrés',
    'comparison.shotsShort': 'Tirs',
    'comparison.shotsMobile': 'TC',
    'comparison.tacklesWon': 'Tacles Réussis',
    'comparison.tacklesShort': 'Tacles',
    'comparison.tacklesMobile': 'Tacl',
    'comparison.totalDistanceDesc': 'Distance totale parcourue pendant le match',
    'comparison.passCompletionDesc': 'Pourcentage de passes réussies',
    'comparison.shotsOnTargetDesc': 'Nombre de tirs cadrés',
    'comparison.tacklesWonDesc': 'Nombre de tacles réussis',
    'comparison.sortBy': 'Trier par',
    'comparison.sortDirection': 'Direction',
    'comparison.clearSort': 'Effacer',
    'comparison.ascending': 'Croissant',
    'comparison.descending': 'Décroissant',
    'comparison.errorLoading': 'Erreur lors du chargement des joueurs',
    'injury.major': 'Majeure',
    'medical.fitness': 'Condition physique',
    'medical.clearance': 'Autorisation médicale',

    // Disciplinary
    'disciplinary.yellowCard': 'Carton jaune',
    'disciplinary.redCard': 'Carton rouge',
    'disciplinary.suspension': 'Suspension',
    'disciplinary.fine': 'Amende',
    'disciplinary.warning': 'Avertissement',
    'disciplinary.record': 'Dossier disciplinaire',

    // Mobile & Responsive
    'mobile.rotateDevice': 'Pour une meilleure visualisation des graphiques, essayez de faire pivoter votre appareil en mode paysage.',
    'mobile.touchHint': 'Appuyez pour plus de détails',

    // Chart & Visualization labels
    'chart.goals': 'Buts',
    'chart.assists': 'Passes décisives',
    'chart.performance': 'Performance',
    'chart.timeline': 'Chronologie',
    'chart.comparison': 'Comparaison',
    'chart.trend': 'Tendance',
    'chart.distribution': 'Distribution',
    'chart.average': 'Moyenne',
    'chart.total': 'Total',
    'chart.percentage': 'Pourcentage',

    // Settings
    'settings.language': 'Langue',
    'settings.theme': 'Thème',
    'settings.profile': 'Profil',
    'settings.preferences': 'Préférences',
    'settings.notifications': 'Notifications',
    'settings.privacy': 'Confidentialité',
    'settings.account': 'Compte',

    // Page titles and descriptions
    'page.dashboard.title': 'Tableau de Bord',
    'page.dashboard.description': 'Vue d\'ensemble des performances et métriques clés',
    'page.playerStats.title': 'Statistiques Joueur',
    'page.playerStats.description': 'Analysez les performances individuelles et les statistiques détaillées',
    
    // Player Stats Page
    'playerStats.selectPlayer': 'Sélectionner un joueur',
    'playerStats.searchPlayers': 'Rechercher par nom ou poste...',
    'playerStats.playersAvailable': 'joueurs disponibles',
    'playerStats.noPlayersFound': 'Aucun joueur trouvé',
    'playerStats.playerProfile': 'Profil Joueur',
    'playerStats.currentForm': 'Forme Actuelle',
    'playerStats.excellentForm': 'Excellente Forme',
    'playerStats.goodForm': 'Bonne Forme',
    'playerStats.averageForm': 'Forme Moyenne',
    'playerStats.poorForm': 'Forme Médiocre',
    'playerStats.contract': 'Contrat',
    'playerStats.daysLeft': 'jours restants',
    'playerStats.fitness': 'Condition',
    'playerStats.lowRisk': 'Risque Faible',
    'playerStats.discipline': 'Discipline',
    'playerStats.topAttributes': 'Principales Qualités',
    'playerStats.workRate': 'Intensité de Jeu',
    'playerStats.skillMoves': 'Gestes Techniques',
    'playerStats.weakFoot': 'Pied Faible',
    'playerStats.leadership': 'Leadership',
    'playerStats.mentalStrength': 'Force Mentale',
    'playerStats.viewSchedule': 'Voir Calendrier',
    'playerStats.performanceTrends': 'Tendances Performance',
    'playerStats.trainingHistory': 'Historique Entraînement',
    
    // Match Performance
    'playerStats.matchByMatch': 'Performance Match par Match',
    'playerStats.recentMatches': 'Performances récentes et statistiques',
    'playerStats.loadingMatches': 'Chargement des performances...',
    'playerStats.noMatches': 'Aucune performance disponible',
    'playerStats.noMatchData': 'Aucune donnée de match récente enregistrée',
    'playerStats.lastMatches': 'derniers matchs',
    'playerStats.rating': 'Note',
    'playerStats.minutes': 'Minutes',
    'playerStats.date': 'Date',
    'playerStats.goalsAssists': 'Buts + Passes',
    'playerStats.shotsOnTarget': 'Tirs Cadrés',
    'playerStats.passAccuracy': 'Précision Passes',
    'playerStats.distance': 'Distance',
    'playerStats.showingLast10': 'Affichage des 10 derniers matchs. Analyse détaillée dans les rapports.',
    
    // Player Selection  
    'playerStats.roleAccess.player': 'Vous ne pouvez voir que vos propres statistiques et données de performance.',
    'playerStats.roleAccess.loading': 'Chargement de votre profil joueur...',
    'playerStats.roleAccess.loadingStats': 'Veuillez patienter pendant que nous chargeons vos statistiques',
    
    // Stat Cards
    'playerStats.stats.matches': 'Matchs',
    'playerStats.stats.goals': 'Buts',
    'playerStats.stats.assists': 'Passes',
    'playerStats.stats.rating': 'Note',
    'playerStats.stats.distance': 'Distance',
    'playerStats.stats.passAccuracy': 'Précision Passes',
    'playerStats.stats.shotAccuracy': 'Précision Tirs',
    'playerStats.stats.perMatch': 'par match',
    'playerStats.stats.kmTotal': 'km total',
    'playerStats.stats.average': 'Moyenne',
    'page.playerComparison.title': 'Comparaison Joueurs',
    'page.playerComparison.description': 'Comparez jusqu\'à 4 joueurs selon diverses métriques',
    'page.playerDevelopment.title': 'Développement Joueur',
    'page.playerDevelopment.description': 'Suivi du développement et des objectifs des joueurs',
    'page.shotMap.title': 'Carte des Tirs',
    'page.shotMap.description': 'Visualisez et analysez les modèles et résultats de tirs',
    'page.goalsAssists.title': 'Buts et Passes Décisives',
    'page.goalsAssists.description': 'Analyse complète des performances en buts et passes décisives',
    'page.teamOverview.title': 'Aperçu Équipe',
    'page.teamOverview.description': 'Vue d\'ensemble des performances et statistiques de l\'équipe',
    'page.tacticalAnalysis.title': 'Analyse Tactique',
    'page.tacticalAnalysis.description': 'Analyse tactique approfondie et insights stratégiques',
    'page.pointsDeductions.title': 'Pénalités de Points',
    'page.pointsDeductions.description': 'Suivi et analyse de l\'impact des pénalités administratives',
    'page.matchDataImport.title': 'Import Données Match',
    'page.matchDataImport.description': 'Importez et gérez les données de match'
  },
  en: {
    'nav.dashboard': 'Dashboard Home',
    'nav.playerAnalysis': 'Player Analysis',
    'nav.teamPerformance': 'Team Performance',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.individualStats': 'Individual Player Stats',
    'nav.playerComparison': 'Player Comparison',
    'nav.playerDevelopment': 'Player Development',
    'nav.shotMap': 'Shot Map',
    'nav.teamOverview': 'Team Overview',
    'nav.tacticalAnalysis': 'Tactical Analysis',
    'nav.aiAnalytics': 'AI Analytics',
    'header.title': 'Striker Insights Arena',
    'header.dashboard': 'Dashboard'
  },
  ar: {
    'nav.dashboard': 'الصفحة الرئيسية',
    'nav.playerAnalysis': 'تحليل اللاعبين',
    'nav.teamPerformance': 'أداء الفريق',
    'nav.reports': 'التقارير',
    'nav.settings': 'الإعدادات',
    'nav.individualStats': 'إحصائيات اللاعبين الفردية',
    'nav.playerComparison': 'مقارنة اللاعبين',
    'nav.playerDevelopment': 'تطوير اللاعبين',
    'nav.shotMap': 'خريطة التسديد',
    'nav.teamOverview': 'نظرة عامة على الفريق',
    'nav.tacticalAnalysis': 'التحليل التكتيكي',
    'header.title': 'ستريكر إنسايتس أرينا',
    'header.dashboard': 'لوحة التحكم'
  }
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'fr'; // Default to French
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    
    // Apply text direction for Arabic
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
