
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtsrymkdgpzaiobvsobb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0c3J5bWtkZ3B6YWlvYnZzb2JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2MDEwMTYsImV4cCI6MjA2MzE3NzAxNn0.YLaDdrpoi8Xu7iz8ynOJu6q_1SgvJeorlskVq_LNJ2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
